//! Event ABI, topic uniqueness, and schema regression tests.
//!
//! # Issue #1585 — Topic collision prevention
//!
//! Each `#[contractevent]` struct emits a topic vector whose first element is
//! a `Symbol` derived from the struct name in snake_case (generated by the
//! soroban SDK). The remaining topics are the `#[topic]`-annotated fields.
//!
//! This module enforces two invariants that together prevent topic collisions
//! across all lifecycle operations:
//!
//! **Invariant 1 — Unique namespace.**
//! No two event types may share the same `topic[0]` symbol. This is the
//! primary uniqueness key an indexer uses to route events to its handler;
//! a collision would make two distinct event kinds indistinguishable.
//! `test_all_event_topic_names_are_unique` asserts this at runtime by
//! emitting every event type in a single environment and verifying the
//! collected name-symbols form a strictly-sized distinct set.
//!
//! **Invariant 2 — Stable arity and field layout.**
//! For each event, the number of topics (including `topic[0]`) and the set of
//! data-payload field names are frozen as ABI. Any incompatible change — rename
//! a field, drop a topic, reorder topics — causes `test_golden_events` or
//! `test_delegate_events` to fail. Adding a new field at the end of the struct
//! is the only compatible ("additive") change; see the `events.rs` module docs
//! for the full versioning rule.
//!
//! # Versioning rule (enforced by these tests)
//!
//! * **Additive (compatible):** append a new field at the end of the struct.
//!   Indexers that tolerate unknown trailing fields continue to work.
//! * **Breaking:** rename, remove, reorder, or re-topic any existing field, or
//!   change `topic[0]` (which would change the struct name). Introduce a new
//!   struct with a `V2` suffix and keep the old one for the migration window.
//!
//! Both invariants are machine-verifiable: rename an event struct or swap two
//! `#[topic]` fields and these tests fail immediately, before any indexer sees
//! a broken deployment.

#![cfg(test)]

use soroban_sdk::{testutils::Events, vec, Symbol, TryFromVal, TryIntoVal, Val};

use crate::test::common::{Harness, DAY, ONE, T0};
use crate::op;

extern crate std;
use std::string::{String, ToString};
use std::println;

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/// Extract all contract events from the harness environment, map each one to
/// `(topics_vec, data_val)` using the `Val`-level representation, and clear
/// the queue so successive calls return only the new events.
///
/// The returned vec is ordered by emission order.
fn drain_events(h: &Harness) -> std::vec::Vec<(soroban_sdk::Vec<Val>, Val)> {
    let raw = h
        .env
        .events()
        .all()
        .filter_by_contract(&h.contract_id)
        .events()
        .to_vec();

    raw.into_iter()
        .map(|event| {
            let soroban_sdk::xdr::ContractEventBody::V0(body) = event.body;
            let mut topics = soroban_sdk::vec![&h.env];
            for t in body.topics.iter() {
                topics.push_back(soroban_sdk::Val::try_from_val(&h.env, t).unwrap());
            }
            let data: Val = soroban_sdk::Val::try_from_val(&h.env, &body.data).unwrap();
            (topics, data)
        })
        .collect()
}

/// Return the `Symbol` stored at `topic[0]` of an event.
fn topic_name(h: &Harness, event: &(soroban_sdk::Vec<Val>, Val)) -> Symbol {
    event
        .0
        .get(0)
        .expect("every contractevent must have at least one topic")
        .try_into_val(&h.env)
        .expect("topic[0] must be a Symbol")
}

// ---------------------------------------------------------------------------
// Invariant 1 — No two event types share the same topic[0] symbol.
//
// Strategy: emit every one of the 10 event types in a single Env, accumulate
// all events after each operation (soroban's Events::all() only retains the
// most recent invocation, so we must capture eagerly), then assert the
// collected topic[0] symbols are distinct.
//
// Full inventory covered:
//   stream_created, paused, resumed, topped_up, recipient_transferred,
//   withdrawn, cancelled, ttl_extended, delegate_granted, delegate_revoked
// ---------------------------------------------------------------------------

#[test]
fn recipient_transferred_event_emits_stream_and_recipient_fields() {
    let h = Harness::new();
    let stream_id = h.create_simple(100 * ONE, 100 * DAY);

    h.client.transfer_recipient(&stream_id, &h.other);

    let event = drain_events(&h)
        .into_iter()
        .find(|event| topic_name(&h, event) == Symbol::new(&h.env, "recipient_transferred"))
        .expect("transfer_recipient must emit a recipient_transferred event");

    let topics = &event.0;
    assert_eq!(topics.len(), 4, "RecipientTransferred: topic[0] + stream_id + old_recipient + new_recipient = 4");

    let expected_stream_id: Val = stream_id.into_val(&h.env);
    let expected_old_recipient: Val = h.recipient.clone().into_val(&h.env);
    let expected_new_recipient: Val = h.other.clone().into_val(&h.env);

    assert_eq!(topics.get(1).unwrap(), &expected_stream_id);
    assert_eq!(topics.get(2).unwrap(), &expected_old_recipient);
    assert_eq!(topics.get(3).unwrap(), &expected_new_recipient);

    let payload: soroban_sdk::Map<Symbol, Val> = event.1.try_into_val(&h.env).unwrap();
    assert!(payload.is_empty(), "RecipientTransferred payload should be empty data, with all identifying fields in topics");
}

#[test]
fn withdrawn_event_topics_include_stream_id_and_recipient() {
    let h = Harness::new();
    let stream_id = h.create_simple(100 * ONE, 100 * DAY);

    h.advance(30 * DAY);
    h.client.withdraw(&stream_id, &Some(10 * ONE));

    let event = drain_events(&h)
        .into_iter()
        .find(|event| topic_name(&h, event) == Symbol::new(&h.env, "withdrawn"))
        .expect("withdraw must emit a withdrawn event");

    let topics = &event.0;
    assert_eq!(topics.len(), 3, "Withdrawn: topic[0] + stream_id + recipient = 3");

    let expected_stream_id: Val = stream_id.into_val(&h.env);
    let expected_recipient: Val = h.recipient.clone().into_val(&h.env);

    assert_eq!(topics.get(1).unwrap(), &expected_stream_id);
    assert_eq!(topics.get(2).unwrap(), &expected_recipient);

    let payload: soroban_sdk::Map<Symbol, Val> = event.1.try_into_val(&h.env).unwrap();
    assert!(payload.contains_key(Symbol::new(&h.env, "amount")));
    assert!(payload.contains_key(Symbol::new(&h.env, "withdrawn")));
    assert!(payload.contains_key(Symbol::new(&h.env, "deposited")));
    assert!(payload.contains_key(Symbol::new(&h.env, "status")));
}

#[test]
fn test_all_event_topic_names_are_unique() {
    let h = Harness::new();

    // Accumulate all contract events across multiple calls.
    // Events::all() only retains the most recent invocation, so we must
    // snapshot after each call and extend the running list.
    let mut all_events: std::vec::Vec<(soroban_sdk::Vec<Val>, Val)> = std::vec::Vec::new();
    let mut capture = || {
        all_events.extend(drain_events(&h));
    };

    // 1. stream_created
    let id = h.create(100 * ONE, T0, T0 + 10 * DAY, T0, true, true, true);
    capture();

    // 2. paused
    h.client.pause(&id);
    capture();

    h.advance(DAY);

    // 3. resumed
    h.client.resume(&id);
    capture();

    // 4. topped_up
    h.client.top_up(&id, &(10 * ONE));
    capture();

    // 5. recipient_transferred
    h.client.transfer_recipient(&id, &h.other);
    capture();

    h.advance(2 * DAY);

    // 6. withdrawn (recipient is now `other`; auth is mocked globally)
    h.client.withdraw(&id, &Some(5 * ONE));
    capture();

    // 7. cancelled
    h.client.cancel(&id);
    capture();

    // 8. ttl_extended
    h.client.extend_stream_ttl(&id);
    capture();

    // 9–10. delegate events — need a live, non-terminal stream
    let now = h.now();
    let id2 = h.create(100 * ONE, now, now + 10 * DAY, now, true, true, true);
    let delegate = &h.other;

    // 9. delegate_granted
    h.client.grant_delegate(&id2, &h.sender, delegate, &op::CANCEL, &None);
    capture();

    // 10. delegate_revoked
    h.client.revoke_delegate(&id2, &h.sender, delegate);
    capture();

    let events = all_events;

    // Collect the topic[0] symbol of every event as a String.
    // Symbol::to_string() is available in the testutils environment.
    let mut all_names: std::vec::Vec<String> = events
        .iter()
        .map(|e| topic_name(&h, e).to_string())
        .collect();

    println!(
        "All event topic[0] values (emission order): {:?}",
        all_names
    );

    // Build the set of distinct event type names observed across all operations.
    // Some event types (e.g. stream_created) fire more than once because we
    // create two streams.  What we need to assert is:
    //   (a) every expected type was observed at least once, and
    //   (b) no two *different* event struct types share the same name.
    //
    // Condition (b) is equivalent to: the set of distinct observed names matches
    // the expected inventory exactly.
    all_names.sort();
    all_names.dedup();
    let unique_names = all_names; // now sorted, unique

    // The canonical inventory: every event struct's snake_case name.
    // To register a new event: add it here AND add a schema snapshot test in
    // test_golden_events or test_delegate_events.
    let expected: std::vec::Vec<String> = {
        let mut v: std::vec::Vec<String> = std::vec![
            "cancelled".into(),
            "delegate_granted".into(),
            "delegate_revoked".into(),
            "paused".into(),
            "recipient_transferred".into(),
            "resumed".into(),
            "stream_created".into(),
            "topped_up".into(),
            "ttl_extended".into(),
            "withdrawn".into(),
        ];
        v.sort();
        v
    };

    // If there is a collision the deduped set will be smaller than `expected`;
    // if an event type is missing it will differ in content.
    assert_eq!(
        unique_names,
        expected,
        "Event inventory mismatch or TOPIC COLLISION DETECTED.\n\
         A collision means two event structs generated the same snake_case name.\n\
         A mismatch means a new event was added without registering it here,\n\
         or an existing event's struct name changed (a breaking ABI change).\n\n\
         Observed unique topic[0] values: {unique_names:?}\n\
         Expected:                        {expected:?}"
    );

    println!(
        "✓ All {} event types have unique topic[0] symbols: {:?}",
        unique_names.len(),
        unique_names
    );
}

// ---------------------------------------------------------------------------
// Invariant 2a — Golden path: 8 original events (schema + arity snapshot)
// ---------------------------------------------------------------------------

#[test]
fn test_golden_events() {
    let harness = Harness::new();
    let env = &harness.env;
    let _sender = &harness.sender;
    let _recipient = &harness.recipient;
    let _token = &harness.token;
    let other = &harness.other;

    let start = T0;
    let end = T0 + 10 * DAY;
    let cliff = T0;

    let mut raw_events = std::vec::Vec::new();
    let mut push_events = || {
        raw_events.extend(
            env.events()
                .all()
                .filter_by_contract(&harness.contract_id)
                .events()
                .to_vec(),
        );
    };

    // 1. Create Stream
    let stream_id = harness.create(100 * ONE, start, end, cliff, true, true, true);
    push_events();

    // 2. Pause
    harness.client.pause(&stream_id);
    push_events();

    harness.advance(DAY);

    // 3. Resume
    harness.client.resume(&stream_id);
    push_events();

    // 4. Top Up
    harness.client.top_up(&stream_id, &(10 * ONE));
    push_events();

    // 5. Transfer Recipient
    harness.client.transfer_recipient(&stream_id, other);
    push_events();

    harness.advance(2 * DAY);

    // 6. Withdraw
    let _withdrawn_amount = harness.client.withdraw(&stream_id, &Some(5 * ONE));
    push_events();

    // 7. Cancel
    harness.client.cancel(&stream_id);
    push_events();

    // 8. TTL Extended
    harness.client.extend_stream_ttl(&stream_id);
    push_events();
    let mut events = std::vec::Vec::new();
    for event in raw_events {
        let soroban_sdk::xdr::ContractEventBody::V0(body) = event.body;
        let mut topics = soroban_sdk::vec![&env];
        for t in body.topics.iter() {
            topics.push_back(soroban_sdk::Val::try_from_val(env, t).unwrap());
        }
        let data: Val = soroban_sdk::Val::try_from_val(env, &body.data).unwrap();
        events.push((topics, data));
    }

    // We expect exactly 8 events
    assert_eq!(
        events.len(),
        8,
        "Expected exactly 8 events for the golden path"
    );

    // Helper to check standard event structure
    let assert_event_topic = |event: &(soroban_sdk::Vec<Val>, Val), expected_name: &str| {
        let topics = &event.0;
        let topic_symbol: Symbol = topics.get(0).unwrap().try_into_val(env).unwrap();
        assert_eq!(topic_symbol, Symbol::new(env, expected_name));
    };

    assert_event_topic(events.first().unwrap(), "stream_created");
    assert_event_topic(events.get(1).unwrap(), "paused");
    assert_event_topic(events.get(2).unwrap(), "resumed");
    assert_event_topic(events.get(3).unwrap(), "topped_up");
    assert_event_topic(events.get(4).unwrap(), "recipient_transferred");
    assert_event_topic(events.get(5).unwrap(), "withdrawn");
    assert_event_topic(events.get(6).unwrap(), "cancelled");
    assert_event_topic(events.get(7).unwrap(), "ttl_extended");

    // Topic arity assertions (topic[0] + #[topic] fields)
    assert_eq!(
        events.first().unwrap().0.len(),
        4,
        "StreamCreated: topic[0] + stream_id + sender + recipient = 4"
    );
    assert_eq!(
        events.get(1).unwrap().0.len(),
        3,
        "Paused: topic[0] + stream_id + sender = 3"
    );
    assert_eq!(
        events.get(2).unwrap().0.len(),
        3,
        "Resumed: topic[0] + stream_id + sender = 3"
    );
    assert_eq!(
        events.get(3).unwrap().0.len(),
        3,
        "ToppedUp: topic[0] + stream_id + sender = 3"
    );
    assert_eq!(
        events.get(4).unwrap().0.len(),
        4,
        "RecipientTransferred: topic[0] + stream_id + old_recipient + new_recipient = 4"
    );
    assert_eq!(
        events.get(5).unwrap().0.len(),
        3,
        "Withdrawn: topic[0] + stream_id + recipient = 3"
    );
    assert_eq!(
        events.get(6).unwrap().0.len(),
        4,
        "Cancelled: topic[0] + stream_id + sender + recipient = 4"
    );
    assert_eq!(
        events.get(7).unwrap().0.len(),
        2,
        "TtlExtended: topic[0] + stream_id = 2"
    );

    // Detailed schema snapshots verified here via explicit field names and types.
    // By checking the exact map keys, any incompatible change (e.g. renaming a field or removing one)
    // will cause this test to fail, acting as a checked-in schema snapshot.
    let stream_created_payload = events.first().unwrap().1;
    // We expect the payload to be a map of the struct fields
    let map: soroban_sdk::Map<Symbol, Val> = stream_created_payload.try_into_val(env).unwrap();

    // Check all expected field names are present to freeze the ABI
    let expected_fields = vec![
        &env,
        Symbol::new(env, "cancellable"),
        Symbol::new(env, "cliff_time"),
        Symbol::new(env, "deposited"),
        Symbol::new(env, "end_time"),
        Symbol::new(env, "pausable"),
        Symbol::new(env, "start_time"),
        Symbol::new(env, "token"),
        Symbol::new(env, "transferable"),
    ];
    for field in expected_fields.iter() {
        assert!(
            map.contains_key(field.clone()),
            "Missing field in StreamCreated: {:?}",
            field
        );
    }

    let paused_payload: soroban_sdk::Map<Symbol, Val> =
        events.get(1).unwrap().1.try_into_val(env).unwrap();
    assert!(paused_payload.contains_key(Symbol::new(env, "paused_at")));
    assert!(paused_payload.contains_key(Symbol::new(env, "paused_total")));

    let resumed_payload: soroban_sdk::Map<Symbol, Val> =
        events.get(2).unwrap().1.try_into_val(env).unwrap();
    assert!(resumed_payload.contains_key(Symbol::new(env, "paused_duration")));
    assert!(resumed_payload.contains_key(Symbol::new(env, "paused_total")));

    let toppedup_payload: soroban_sdk::Map<Symbol, Val> =
        events.get(3).unwrap().1.try_into_val(env).unwrap();
    assert!(toppedup_payload.contains_key(Symbol::new(env, "amount")));
    assert!(toppedup_payload.contains_key(Symbol::new(env, "deposited")));
    assert!(toppedup_payload.contains_key(Symbol::new(env, "end_time")));

    // RecipientTransferred has no data fields (only topics), so its payload is likely an empty map or it has no fields to assert.
    // We can still verify it deserializes properly.
    let _rt_payload: soroban_sdk::Map<Symbol, Val> =
        events.get(4).unwrap().1.try_into_val(env).unwrap();

    let withdrawn_payload: soroban_sdk::Map<Symbol, Val> =
        events.get(5).unwrap().1.try_into_val(env).unwrap();
    assert!(withdrawn_payload.contains_key(Symbol::new(env, "amount")));
    assert!(withdrawn_payload.contains_key(Symbol::new(env, "deposited")));
    assert!(withdrawn_payload.contains_key(Symbol::new(env, "status")));
    assert!(withdrawn_payload.contains_key(Symbol::new(env, "withdrawn")));

    let cancelled_payload: soroban_sdk::Map<Symbol, Val> =
        events.get(6).unwrap().1.try_into_val(env).unwrap();
    assert!(cancelled_payload.contains_key(Symbol::new(env, "end_time")));
    assert!(cancelled_payload.contains_key(Symbol::new(env, "refunded")));
    assert!(cancelled_payload.contains_key(Symbol::new(env, "vested")));
    assert!(cancelled_payload.contains_key(Symbol::new(env, "withdrawn")));

    let ttl_extended_payload: soroban_sdk::Map<Symbol, Val> =
        events.get(7).unwrap().1.try_into_val(env).unwrap();
    assert!(ttl_extended_payload.contains_key(Symbol::new(env, "extended_to_ledgers")));
}

// ---------------------------------------------------------------------------
// Invariant 2b — Delegate events schema snapshot (previously uncovered)
//
// DelegateGranted and DelegateRevoked share the same topic arity
// (topic[0] + stream_id + grantor + delegate = 4) but have distinct topic[0]
// symbols ("delegate_granted" vs "delegate_revoked"). This test freezes both
// their topic arity and payload field sets, exactly as test_golden_events does
// for the other eight events.
// ---------------------------------------------------------------------------

#[test]
fn test_delegate_events() {
    let harness = Harness::new();
    let env = &harness.env;

    let start = T0;
    let end = T0 + 10 * DAY;
    let cliff = T0;

    // Create a live, non-terminal stream.
    let stream_id = harness.create(100 * ONE, start, end, cliff, true, true, true);

    let delegate = &harness.other;

    // --- DelegateGranted ---
    harness.client.grant_delegate(
        &stream_id,
        &harness.sender,
        delegate,
        &op::CANCEL,
        &Some(end),
    );

    let granted_events: std::vec::Vec<_> = env
        .events()
        .all()
        .filter_by_contract(&harness.contract_id)
        .events()
        .to_vec()
        .into_iter()
        .filter_map(|event| {
            let soroban_sdk::xdr::ContractEventBody::V0(body) = event.body;
            let mut topics = soroban_sdk::vec![&env];
            for t in body.topics.iter() {
                topics.push_back(soroban_sdk::Val::try_from_val(env, t).unwrap());
            }
            let data: Val = soroban_sdk::Val::try_from_val(env, &body.data).unwrap();
            // Only keep events whose topic[0] is "delegate_granted"
            let sym: Symbol = topics.get(0)?.try_into_val(env).ok()?;
            if sym == Symbol::new(env, "delegate_granted") {
                Some((topics, data))
            } else {
                None
            }
        })
        .collect();

    assert_eq!(
        granted_events.len(),
        1,
        "grant_delegate must emit exactly one delegate_granted event"
    );

    let (granted_topics, granted_data) = &granted_events[0];

    // Topic[0] name
    let granted_name: Symbol = granted_topics
        .get(0)
        .unwrap()
        .try_into_val(env)
        .unwrap();
    assert_eq!(
        granted_name,
        Symbol::new(env, "delegate_granted"),
        "DelegateGranted topic[0] must be 'delegate_granted'"
    );

    // Arity: topic[0] + stream_id + grantor + delegate = 4
    assert_eq!(
        granted_topics.len(),
        4,
        "DelegateGranted: topic[0] + stream_id + grantor + delegate = 4"
    );

    // Payload field schema
    let granted_payload: soroban_sdk::Map<Symbol, Val> =
        granted_data.try_into_val(env).unwrap();
    assert!(
        granted_payload.contains_key(Symbol::new(env, "ops")),
        "DelegateGranted payload must contain 'ops'"
    );
    assert!(
        granted_payload.contains_key(Symbol::new(env, "expires_at")),
        "DelegateGranted payload must contain 'expires_at'"
    );

    // --- DelegateRevoked ---
    harness.client.revoke_delegate(&stream_id, &harness.sender, delegate);

    let revoked_events: std::vec::Vec<_> = env
        .events()
        .all()
        .filter_by_contract(&harness.contract_id)
        .events()
        .to_vec()
        .into_iter()
        .filter_map(|event| {
            let soroban_sdk::xdr::ContractEventBody::V0(body) = event.body;
            let mut topics = soroban_sdk::vec![&env];
            for t in body.topics.iter() {
                topics.push_back(soroban_sdk::Val::try_from_val(env, t).unwrap());
            }
            let data: Val = soroban_sdk::Val::try_from_val(env, &body.data).unwrap();
            let sym: Symbol = topics.get(0)?.try_into_val(env).ok()?;
            if sym == Symbol::new(env, "delegate_revoked") {
                Some((topics, data))
            } else {
                None
            }
        })
        .collect();

    assert_eq!(
        revoked_events.len(),
        1,
        "revoke_delegate must emit exactly one delegate_revoked event"
    );

    let (revoked_topics, revoked_data) = &revoked_events[0];

    // Topic[0] name
    let revoked_name: Symbol = revoked_topics
        .get(0)
        .unwrap()
        .try_into_val(env)
        .unwrap();
    assert_eq!(
        revoked_name,
        Symbol::new(env, "delegate_revoked"),
        "DelegateRevoked topic[0] must be 'delegate_revoked'"
    );

    // Arity: topic[0] + stream_id + grantor + delegate = 4
    assert_eq!(
        revoked_topics.len(),
        4,
        "DelegateRevoked: topic[0] + stream_id + grantor + delegate = 4"
    );

    // Payload: DelegateRevoked has no data fields (all information is in topics).
    // Verify it deserializes cleanly.
    let _revoked_payload: soroban_sdk::Map<Symbol, Val> =
        revoked_data.try_into_val(env).unwrap();

    // Critically: the two delegate events must have DIFFERENT topic[0] values.
    // This is the direct collision check for the most structurally-similar pair.
    assert_ne!(
        granted_name,
        revoked_name,
        "COLLISION: delegate_granted and delegate_revoked must have different topic[0] symbols"
    );

    println!(
        "✓ DelegateGranted topic[0]={:?}, arity={}, payload fields: [ops, expires_at]",
        granted_name,
        granted_topics.len()
    );
    println!(
        "✓ DelegateRevoked topic[0]={:?}, arity={}, no data payload",
        revoked_name,
        revoked_topics.len()
    );
}

// ---------------------------------------------------------------------------
// No event emitted when a call is rejected
// ---------------------------------------------------------------------------

#[test]
fn test_no_event_on_failure() {
    let harness = Harness::new();
    let env = &harness.env;
    let start = T0;

    // Create an invalid stream (end < start) which should fail
    let res = harness.client.try_create_stream(
        &harness.sender,
        &harness.recipient,
        &harness.token,
        &(100 * ONE),
        &start,
        &(start - 100), // invalid end time
        &start,
        &true,
        &true,
        &true,
    );

    assert!(res.is_err(), "Stream creation should fail");

    let raw_events = env.events().all().events().to_vec();
    assert_eq!(
        raw_events.len(),
        0,
        "No events should be emitted on rejected calls"
    );
}
